///Jordan Liu - declarations of various helper functions e.g. printBatch, makeMesh

#ifndef HELPER_FUNCTIONS_H
#define HELPER_FUNCTIONS_H

#include <iostream>
#include <sstream>
#include <vector>
#include "Greek.h"
#include "US_Perpetual.h"
#include "EUroOption.h"
using namespace std;

void printBatch(int batch_num, double call, double put); //simple print functions to make life easier
void printParity(double call, double put, bool verify);

vector<double> makeMesh(double start, double end, double h); //generate mesh array of S values
void printMesh(const vector<double>& S_values, const vector<double>& call_prices, const vector<double>& put_prices); //print mesh
void printMeshPrice(const vector<double>& prices); //for printing a price mesh generated by matrix pricer

vector<pair<string, double>> makeMeshPair(double start, double end, double h, string param); //for making a mesh of paired doubles and strings
void printMatrix(const vector<vector<double>>& matrix); //print matrix
void printMatrixPair(const vector<vector<pair<string, double>>>& matrix); //adjusted version of printMatrix specifically for printing matrices of pairs

void printGreeks(const Greek& batch, int batch_num); //for printing all the option sensitivities of a given batch
//compare S-value vector, exact delta vector, and DD delta vector, plus a title string
void printCompare(const vector<double>& S_values, Greek& batch, double h);

#endif